import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ClientProviders from "@/components/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Walmart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  model_auth,
  model,
}: Readonly<{
  children: React.ReactNode;
  model_auth: React.ReactNode;
  model: React.ReactNode;
}>) {
  return (
    <ClientProviders>
    <html lang="en">
      <body className={inter.className}>
        < Header />
        <div className="flex">
          {model}
          {model_auth}
          {children}
        </div>
        
        </body>
    </html>
    </ClientProviders>
  );
}
